# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER cxblog

# 挂载目录
VOLUME /home/cxblog
# 创建目录
RUN mkdir -p /home/cxblog
# 指定路径
WORKDIR /home/cxblog
# 复制jar文件到路径
COPY ./jar/cxblog-modules-file.jar /home/cxblog/cxblog-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","cxblog-modules-file.jar"]