# 基础镜像
FROM redis
# author
MAINTAINER cxblog

# 挂载目录
VOLUME /home/cxblog/redis
# 创建目录
RUN mkdir -p /home/cxblog/redis
# 指定路径
WORKDIR /home/cxblog/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/cxblog/redis/redis.conf
