version : '3.8'
services:
  cxblog-nacos:
    container_name: cxblog-nacos
    image: nacos/nacos-server
    build:
      context: ./nacos
    environment:
      - MODE=standalone
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - cxblog-mysql
  cxblog-mysql:
    container_name: cxblog-mysql
    image: mysql:5.7
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_DATABASE: 'ry-cloud'
      MYSQL_ROOT_PASSWORD: password
  cxblog-redis:
    container_name: cxblog-redis
    image: redis
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/cxblog/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/cxblog/redis/redis.conf
  cxblog-nginx:
    container_name: cxblog-nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/home/cxblog/projects/cxblog-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - cxblog-gateway
    links:
      - cxblog-gateway
  cxblog-gateway:
    container_name: cxblog-gateway
    build:
      context: ./cxblog/gateway
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - cxblog-redis
    links:
      - cxblog-redis
  cxblog-auth:
    container_name: cxblog-auth
    build:
      context: ./cxblog/auth
      dockerfile: dockerfile
    ports:
      - "9200:9200"
    depends_on:
      - cxblog-redis
    links:
      - cxblog-redis
  cxblog-modules-system:
    container_name: cxblog-modules-system
    build:
      context: ./cxblog/modules/system
      dockerfile: dockerfile
    ports:
      - "9201:9201"
    depends_on:
      - cxblog-redis
      - cxblog-mysql
    links:
      - cxblog-redis
      - cxblog-mysql
  cxblog-modules-gen:
    container_name: cxblog-modules-gen
    build:
      context: ./cxblog/modules/gen
      dockerfile: dockerfile
    ports:
      - "9202:9202"
    depends_on:
      - cxblog-mysql
    links:
      - cxblog-mysql
  cxblog-modules-job:
    container_name: cxblog-modules-job
    build:
      context: ./cxblog/modules/job
      dockerfile: dockerfile
    ports:
      - "9203:9203"
    depends_on:
      - cxblog-mysql
    links:
      - cxblog-mysql
  cxblog-modules-file:
    container_name: cxblog-modules-file
    build:
      context: ./cxblog/modules/file
      dockerfile: dockerfile
    ports:
      - "9300:9300"
    volumes:
    - ./cxblog/uploadPath:/home/cxblog/uploadPath
  cxblog-visual-monitor:
    container_name: cxblog-visual-monitor
    build:
      context: ./cxblog/visual/monitor
      dockerfile: dockerfile
    ports:
      - "9100:9100"
